services:
  # Center Deep - Standalone Search Engine (No SearXNG dependency)
  center-deep:
    build: .
    image: center-deep:latest
    container_name: center-deep
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ./instance:/app/instance
      - ./data:/app/data
      - ./logs:/app/logs
      - ./static:/app/static:ro
      - ./templates:/app/templates:ro
    networks:
      - center-deep-network
    environment:
      - PORT=8888
      - FLASK_ENV=production
      # Redis configuration - optional but recommended
      - USE_REDIS=${USE_REDIS:-true}
      - REDIS_HOST=redis-cache
      - REDIS_PORT=6379
    depends_on:
      - redis-cache
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  # Redis Cache (Optional but Recommended - improves performance)
  redis-cache:
    image: redis:7-alpine
    container_name: center-deep-redis
    restart: unless-stopped
    ports:
      - "6385:6379"  # Using 6385 to avoid conflicts
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no
    volumes:
      - redis_data:/data
    networks:
      - center-deep-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  center-deep-network:
    name: center-deep-net
    driver: bridge

volumes:
  redis_data:
    name: center-deep-redis-data