version: '3.8'

services:
  # Tool Servers - Using high ports (11000 range) to avoid conflicts
  # Configured to use Gemma 3 models via model switching and iGPU services
  # Model assignments optimized for each tool type
  
  tool-search:
    build: ./toolserver/search
    container_name: center-deep-tool-search
    restart: unless-stopped
    ports:
      - "11001:8001"
    environment:
      - SEARXNG_URL=http://unicorn-searxng:8080
      - CENTER_DEEP_URL=http://center-deep:8888
      - LLM_API_BASE=${LLM_API_BASE:-}
      - LLM_API_KEY=${LLM_API_KEY:-dummy-key}
      - LLM_MODEL=${LLM_MODEL:-gpt-3.5-turbo}
      - TOOL_TYPE=search
    networks:
      - unicorn-network
    labels:
      - "center-deep.tool=search"
      - "center-deep.description=Basic web search functionality"
      - "center-deep.port=11001"
      - "center-deep.openai-compatible=true"
  
  tool-deep-search:
    build: ./toolserver/deep-search
    container_name: center-deep-tool-deep-search
    restart: unless-stopped
    ports:
      - "11002:8002"
    environment:
      - SEARXNG_URL=http://unicorn-searxng:8080
      - CENTER_DEEP_URL=http://center-deep:8888
      - LLM_API_BASE=${LLM_API_BASE:-}
      - LLM_API_KEY=${LLM_API_KEY:-dummy-key}
      - LLM_MODEL=${LLM_MODEL:-gpt-4}
      - TOOL_TYPE=deep-search
    networks:
      - unicorn-network
    labels:
      - "center-deep.tool=deep-search"
      - "center-deep.description=Advanced multi-source search with content extraction"
      - "center-deep.port=11002"
      - "center-deep.openai-compatible=true"
  
  tool-report:
    build: ./toolserver/report
    container_name: center-deep-tool-report
    restart: unless-stopped
    ports:
      - "11003:8003"
    environment:
      - SEARXNG_URL=http://unicorn-searxng:8080
      - CENTER_DEEP_URL=http://center-deep:8888
      - LLM_API_BASE=${LLM_API_BASE:-}
      - LLM_API_KEY=${LLM_API_KEY:-dummy-key}
      - LLM_MODEL=${LLM_MODEL:-gpt-4}
      - TOOL_TYPE=report
    networks:
      - unicorn-network
    labels:
      - "center-deep.tool=report"
      - "center-deep.description=Professional report generation with citations"
      - "center-deep.port=11003"
      - "center-deep.openai-compatible=true"
  
  tool-academic:
    build: ./toolserver/academic
    container_name: center-deep-tool-academic
    restart: unless-stopped
    ports:
      - "11004:8004"
    environment:
      - SEARXNG_URL=http://unicorn-searxng:8080
      - CENTER_DEEP_URL=http://center-deep:8888
      - LLM_API_BASE=${LLM_API_BASE:-}
      - LLM_API_KEY=${LLM_API_KEY:-dummy-key}
      - LLM_MODEL=${LLM_MODEL:-gpt-4}
      - TOOL_TYPE=academic
    networks:
      - unicorn-network
    labels:
      - "center-deep.tool=academic"
      - "center-deep.description=Academic paper generation with proper formatting"
      - "center-deep.port=11004"
      - "center-deep.openai-compatible=true"

networks:
  unicorn-network:
    external: true